server:
  port: 8080
  servlet:
    session:
      timeout: 5m
    context-path: /rest/zhysunny/scaffold

#数据库配置
spring:
  profiles:
    active: ${profile:dev}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/scaffold
    username: root
    password: 123456
    dbcp2:
      max-idle: 10
      min-idle: 1
      initial-size: 1
      max-wait-millis: 1000
#mybatis配置
mybatis:
  mapper-locations: mybatis/*.xml
  type-aliases-package: com.zhysunny.scaffold.pojo
